# Generated by Django 5.1.2 on 2024-11-10 01:38

from django.db import migrations

DEFAULTS = [
    'general'
]


def add_categories(apps, schema_editor):
    Category = apps.get_model('app', 'Category')
    for category_name in DEFAULTS:
        Category.objects.create(name=category_name)

def remove_categories(apps, schema_editor):
    Category = apps.get_model('app', 'Category')
    Category.objects.filter(name__in=DEFAULTS).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_category_task_created_by_alter_taskrecord_status_and_more'),
    ]

    operations = [
        migrations.RunPython(add_categories, remove_categories)
    ]
